/*
 * MainWindow.java
 *
 * Created on __DATE__, __TIME__
 */

package edu.csu.speedo.ui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.Timer;
import java.util.Vector;

import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import edu.csu.speedo.download.ReadAssignFile;
import edu.csu.speedo.download.WriteAssignFile;
import edu.csu.speedo.model.ModelUser;


/**
 *
 * @author  __USER__
 */
public class MainWindow extends javax.swing.JFrame {

	/** Creates new form MainWindow */
	//换肤背景图片
	static String imageName = "img/background5.jpg";
	static Image image = Toolkit.getDefaultToolkit().getImage(imageName);
	//当前使用的ModelNum
	public static int modelNum = 0;

	//主窗体
	public MainWindow() {
		
		try {
			new ReadAssignFile().readAssignFile();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		this.addWindowListener(new WindowClose());
		setWindowIcon();
		initComponents();
		//		jTable1.setCellEditor(anEditor)

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new JImagePane(image, JImagePane.SCALED);
		jButton8 = new javax.swing.JButton();
		jToolBar1 = new javax.swing.JToolBar();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jToolBar2 = new javax.swing.JToolBar();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox();
		jTextField1 = new javax.swing.JTextField();
		jButton9 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable(){
			// 设置jtable的单元格为透明的  
			 public Component prepareRenderer(TableCellRenderer renderer,int row,int column) 
			{    Component c = super.prepareRenderer(renderer, row, column);    
			if (c instanceof JComponent)
			 {     
			((JComponent) c).setOpaque(false);  
			  }  
			  return c;  
			 }
			};
			
//		jScrollPane1.setOpaque(false);
//		jScrollPane1.getViewport().setOpaque(false);
//		jTable1.setShowGrid(false);//设置无边框
		  

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Speedo\u4e0b\u8f7d\u5668");
//		setBounds(new java.awt.Rectangle(450, 200, 0, 0));
		
		Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
		int width = 900;
		int height = 600;
		setBounds((d.width - width) / 2, (d.height - height) / 2, width, height);
		

		jPanel1.setBackground(new java.awt.Color(51, 204, 255));
		jPanel1.setAlignmentX(0.0F);
		jPanel1.setAlignmentY(0.0F);

		jButton8.setIcon(new javax.swing.ImageIcon(
				"img/skin.png")); // NOI18N
		jButton8.setSize(50, 50);
		jButton8.setToolTipText("喜欢什么的背景，你的下载器你做主！");
		jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton8MouseClicked(evt);

			}
		});
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jToolBar1.setFloatable(false);
		jToolBar1.setOrientation(1);
		jToolBar1.setRollover(true);

		jButton1.setFont(new java.awt.Font("微软雅黑", 1, 14));
		jButton1.setIcon(new javax.swing.ImageIcon(
				"img/all.png")); // NOI18N
		jButton1.setFocusable(false);
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		jButton1.setText("\u5168\u90e8\u4efb\u52a1     ");
		jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton1);

		jButton2.setFont(new java.awt.Font("微软雅黑", 1, 14));
		jButton2.setIcon(new javax.swing.ImageIcon(
				"img/doing.png")); // NOI18N
		jButton2.setFocusable(false);
		jButton2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		jButton2.setText("\u6b63\u5728\u4e0b\u8f7d     ");
		jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton2);

		jButton3.setFont(new java.awt.Font("微软雅黑", 1, 14));
		jButton3.setIcon(new javax.swing.ImageIcon(
				"img/doned.png")); // NOI18N
		jButton3.setText("\u4e0b\u8f7d\u5b8c\u6210     ");
		jButton3.setFocusable(false);
		jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton3);

		jToolBar2.setFloatable(false);
		jToolBar2.setRollover(true);
		jToolBar2.setAlignmentY(0.5F);

		jButton4.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jButton4.setIcon(new javax.swing.ImageIcon(
				"img/new.png")); // NOI18N
		jButton4.setFocusable(false);
		jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		jButton4.setLabel("\u65b0\u5efa");
		jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton4MouseClicked(evt);
			}
		});
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jToolBar2.add(jButton4);

		jButton5.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jButton5.setIcon(new javax.swing.ImageIcon(
				"img/resume.png")); // NOI18N
		jButton5.setFocusable(false);
		jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		jButton5.setLabel("\u5f00\u59cb");
		jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jToolBar2.add(jButton5);

		jButton6.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jButton6.setIcon(new javax.swing.ImageIcon(
				"img/stop.png")); // NOI18N
		jButton6.setText("\u6682\u505c");
		jButton6.setFocusable(false);
		jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jToolBar2.add(jButton6);

		jButton7.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jButton7.setIcon(new javax.swing.ImageIcon(
				"img/stop2.png")); // NOI18N
		jButton7.setText("\u5220\u9664");
		jButton7.setFocusable(false);
		jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		jToolBar2.add(jButton7);
		
		jTable1.setFont(new java.awt.Font("微软雅黑", 1, 13));
		jTable1.setModel(ModelUser.dateModel);
		jTable1.setRowHeight(45);
		jTable1.setOpaque(false);
		jTable1.setShowGrid(false);
		
		jScrollPane1.setViewportView(jTable1);
		jScrollPane1.setOpaque(false);
		jScrollPane1.getViewport().setOpaque(false);
		

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"图片", "音乐", "视频" }));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});
		jToolBar2.add(jComboBox1);

		jTextField1.setForeground(new java.awt.Color(153, 153, 153));
		jTextField1.setText("\u97f3\u4e50/\u56fe\u7247/\u89c6\u9891");
		jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField1MouseClicked(evt);
			}
		});
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actionPerformed(evt);
			}
		});
		jToolBar2.add(jTextField1);
		//123
		jButton9.setIcon(new javax.swing.ImageIcon(
				"img/find.png"));
		//123
		//jButton9.setText("\u641c\u7d22");
		jButton9.setFocusable(false);
		jButton9.setToolTipText("需要什么资源，搜一下？");
		jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);		
			}
		});
		jToolBar2.add(jButton9);

//		jTable1.setFont(new java.awt.Font("微软雅黑", 0, 10));
//		jTable1.setModel(new javax.swing.table.DefaultTableModel(
//				new Object[][] {
//
//				}, new String[] { "状态", "文件名", "大小", "进度", "速度", "剩余时间" }) {
//			boolean[] canEdit = new boolean[] { false, false, false, false,
//					false, false };
//
//			public boolean isCellEditable(int rowIndex, int columnIndex) {
//				return canEdit[columnIndex];
//			}
//		});
//		jTable1.setRowHeight(28);
//		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jToolBar1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												138,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																612,
																Short.MAX_VALUE)
														.addComponent(
																jToolBar2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																612,
																Short.MAX_VALUE)))
						.addComponent(jButton8,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.PREFERRED_SIZE, 20,
								javax.swing.GroupLayout.PREFERRED_SIZE));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jButton8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												21,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(66, 66, 66)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jToolBar1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																443,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jToolBar2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				43,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				392,
																				Short.MAX_VALUE)))
										.addGap(52, 52, 52)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

//		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//搜索事件响应
		String key = jTextField1.getText();
		String s=(String)jComboBox1.getSelectedItem();
		System.out.println(123123);
		if(s.equals("图片"))
		{
			String keyUrl = "http://image.baidu.com/i?word="+key;
			try {
				Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " +keyUrl);
				
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		else if(s.equals("音乐"))
		{
			String keyUrl =  "http://music.baidu.com/search?key="+key;
			try {
				Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + keyUrl);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		else
		{//视频
			String keyUrl =  "http://video.baidu.com/v?word="+key;
			try {
				Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + keyUrl);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
	}

	private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		//搜索框
		jTextField1.setText("");
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//窗口关闭类
		class WindowClose extends WindowAdapter
		{
			public void windowClosing(WindowEvent e)
			{
				System.out.println("closing");
				try {
					WriteAssignFile.writeFile();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		}
	//输出ModleUser
	//	public  void saveModel()
	//	{
	//
	//		try {
	//			FileOutputStream fo = new FileOutputStream("C:/Users/lin/Desktop/testfile/spddate");
	//			ObjectOutputStream os = new ObjectOutputStream(fo);
	//			os.writeObject(ModelUser.dateModel);
	//			os.flush();
	//			
	//		} catch (FileNotFoundException e) {
	//			// TODO Auto-generated catch block
	//			e.printStackTrace();
	//		} catch (IOException e) {
	//			// TODO Auto-generated catch block
	//			e.printStackTrace();
	//		}	
	//	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//已完成触发事件
		jTable1.setModel(ModelUser.dateModelFinish);
		modelNum = 2;
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//暂停按钮触发事件
		if (modelNum == 0) {//全部任务
			int stopNum = jTable1.getSelectedRow();
			if (stopNum != -1) {
				ModelUser.getRunn(stopNum).terminate();
				ModelUser.setValue("暂停", stopNum, 0);
				//同时刷新正在下载Table
				String src = ModelUser.getRowUrl(stopNum);
				int index = ModelUser.getRowDL(src);
				ModelUser.setValueDLModel("暂停", index, 0);
			}
		} else if (modelNum == 1) {//正在下载
			int stopNum = jTable1.getSelectedRow();
			if (stopNum != -1) {
				ModelUser.getRunnDL(stopNum).terminate();
				ModelUser.setValueDLModel("暂停", stopNum, 0);
				//同时刷新全部任务Table
				String src = ModelUser.getRowUrlDL(stopNum);
				int index = ModelUser.getRow(src);
				ModelUser.setValue("暂停", index, 0);
			}
		}
		//已完成...
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//删除按钮触发事件
		//		Timer time = new Timer();

		int Rnum = JOptionPane.showConfirmDialog(null, "是否在删除任务的同时删除源文件？",
				"请选择", JOptionPane.YES_NO_CANCEL_OPTION);
		if (Rnum == 0) //是
		{
			System.out.println("11111111111");
			int deleteNum = jTable1.getSelectedRow();
			if (deleteNum != -1) {
				if (modelNum == 0) {//从全部任务Table删除
					String finishFlat = ModelUser.getResInf(deleteNum).get(4)
							.toString(); //是否完成标识
					if (finishFlat.equals("false")) {//判断任务是否已经下载完成
						ModelUser.getRunn(deleteNum).terminate(); //暂停选定线程
						ModelUser.runnables.get(deleteNum).setDestory(); //中止线程
					}
					ModelUser.removeRow(deleteNum); //删除列表中对应列
					String src = ModelUser.getRowUrl(deleteNum); //返回此任务URL（唯一）
					ModelUser.removeUrl(deleteNum); //删除urls中对应url
					ModelUser.removeRunnable(deleteNum); //删除runnables对应runnable
					ModelUser.removeVector(deleteNum); //删除vector列表存储对应列信息的vector

					if (finishFlat.equals("false")) {//如果文件正在下载,删除正在下载列表对应的所有信息
						int deleteDLnum = ModelUser.getRowDL(src);
						ModelUser.removeRowDLModel(deleteDLnum);
						ModelUser.removeUrlDL(deleteDLnum);
						ModelUser.removeRunnableDL(deleteDLnum);
					} else {//文件已完成
						int deleteFSnum = ModelUser.getRowFS(src);
						ModelUser.removeRowFSModel(deleteFSnum);
						ModelUser.removeUrlFS(deleteFSnum);
					}
					//从allDownloadDateInf中获取对应的文件存储dest=============================
					String dest = ModelUser.getResInf(deleteNum).get(1)
							.toString();
					System.out.println(dest);

					File file = new File(dest + "/"
							+ ModelUser.getResInf(deleteNum).get(3).toString());
					if (file.exists()) {//删除文件
						file.delete();
					}
					File asfile = new File(dest + "/"
							+ ModelUser.getResInf(deleteNum).get(2).toString()
							+ ".spd");
					if (asfile.exists()) {//删除配置文件
						asfile.delete();
					}
					ModelUser.removeResInf(deleteNum); //删除resourceInf中对应的resourceinf vector
				} else if (modelNum == 1) {//从正在下载Table删除
					ModelUser.getRunn(deleteNum).terminate(); //暂停选定线程
					ModelUser.runnablesDL.get(deleteNum).setDestory(); //中止线程
					String src = ModelUser.getRowUrlDL(deleteNum); //提取URL （全局唯一）
					//将正在下载对应信息删除
					ModelUser.removeUrlDL(deleteNum);
					ModelUser.removeRowDLModel(deleteNum);
					ModelUser.removeRunnableDL(deleteNum);
					//删除全部信息Table对应的数据
					int deleteNumAll = ModelUser.getRow(src);
					ModelUser.removeRow(deleteNumAll);
					ModelUser.removeRunnable(deleteNumAll);
					ModelUser.removeUrl(deleteNumAll);
					ModelUser.removeVector(deleteNumAll);

					//从allDownloadDateInf中获取对应的文件存储dest=============================
					String dest = ModelUser.getResInf(deleteNumAll).get(1)
							.toString();
					File file = new File(dest
							+ "/"
							+ ModelUser.getResInf(deleteNumAll).get(3)
									.toString());
					if (file.exists()) {//删除文件
						file.delete();
					}
					File asfile = new File(dest
							+ "/"
							+ ModelUser.getResInf(deleteNumAll).get(2)
									.toString() + ".spd");
					if (asfile.exists()) {//删除配置文件
						asfile.delete();
					}
					ModelUser.removeResInf(deleteNumAll); //删除resourceInf中对应的resourceinf vector					
				} else {//从下载完成Table删除
						//将下载完成对应信息删除
					String src = ModelUser.getRowUrlFS(deleteNum); //提取URL （全局唯一）
					ModelUser.removeRowFSModel(deleteNum);
					ModelUser.removeUrlFS(deleteNum);
					//删除全部信息Table对应的数据
					int deleteNumAll = ModelUser.getRow(src);
					ModelUser.removeRow(deleteNumAll);
					ModelUser.removeRunnable(deleteNumAll);
					ModelUser.removeUrl(deleteNumAll);
					ModelUser.removeVector(deleteNumAll);

					//从allDownloadDateInf中获取对应的文件存储dest=============================
					String dest = ModelUser.getResInf(deleteNumAll).get(1)
							.toString();
					File file = new File(dest
							+ "/"
							+ ModelUser.getResInf(deleteNumAll).get(3)
									.toString());
					if (file.exists()) {//删除文件
						file.delete();
					}
					File asfile = new File(dest
							+ "/"
							+ ModelUser.getResInf(deleteNumAll).get(2)
									.toString() + ".spd");
					if (asfile.exists()) {//删除配置文件
						asfile.delete();
					}
					ModelUser.removeResInf(deleteNumAll); //删除resourceInf中对应的resourceinf vector
				}
			}
		}
		if (Rnum == 1) //否
		{
			int deleteNum = jTable1.getSelectedRow();
			if (deleteNum != -1) {
				if (modelNum == 0) {//从全部任务Table删除
					String finishFlat = ModelUser.getResInf(deleteNum).get(4)
							.toString(); //是否完成标识
					System.out.println(finishFlat);
					if (finishFlat.equals("false")) //判断任务是否已经下载完成
						ModelUser.runnables.get(deleteNum).setDestory(); //中止线程

					ModelUser.removeRow(deleteNum); //删除列表中对应列
					String src = ModelUser.getRowUrl(deleteNum); //返回此任务URL（唯一）
					ModelUser.removeUrl(deleteNum); //删除urls中对应url
					ModelUser.removeRunnable(deleteNum); //删除runnables对应runnable
					ModelUser.removeResInf(deleteNum); //删除resourceInf中对应的resourceinf vector
					ModelUser.removeVector(deleteNum); //删除vector列表存储对应列信息的vector

					if (finishFlat.equals("false")) {//如果文件正在下载,删除正在下载列表对应的所有信息
						int deleteDLnum = ModelUser.getRowDL(src);
						ModelUser.removeRowDLModel(deleteDLnum);
						ModelUser.removeUrlDL(deleteDLnum);
						ModelUser.removeRunnableDL(deleteDLnum);
					} else {//文件已完成
						int deleteFSnum = ModelUser.getRowFS(src);
						ModelUser.removeRowFSModel(deleteFSnum);
						ModelUser.removeUrlFS(deleteFSnum);
					}
				} else if (modelNum == 1) {//从正在下载Table删除
					ModelUser.runnablesDL.get(deleteNum).setDestory(); //中止线程
					String src = ModelUser.getRowUrlDL(deleteNum); //提取URL （全局唯一）
					//将正在下载对应信息删除
					ModelUser.removeUrlDL(deleteNum);
					ModelUser.removeRowDLModel(deleteNum);
					ModelUser.removeRunnableDL(deleteNum);
					//删除全部信息Table对应的数据
					int deleteNumAll = ModelUser.getRow(src);
					ModelUser.removeResInf(deleteNumAll);
					ModelUser.removeRow(deleteNumAll);
					ModelUser.removeRunnable(deleteNumAll);
					ModelUser.removeUrl(deleteNumAll);
					ModelUser.removeVector(deleteNumAll);
				} else {//从下载完成Table删除
						//将下载完成对应信息删除
					String src = ModelUser.getRowUrlFS(deleteNum); //提取URL （全局唯一）
					ModelUser.removeRowFSModel(deleteNum);
					ModelUser.removeUrlFS(deleteNum);
					//删除全部信息Table对应的数据
					int deleteNumAll = ModelUser.getRow(src);
					ModelUser.removeResInf(deleteNumAll);
					ModelUser.removeRow(deleteNumAll);
					ModelUser.removeRunnable(deleteNumAll);
					ModelUser.removeUrl(deleteNumAll);
					ModelUser.removeVector(deleteNumAll);
				}
			}
		}
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		//点击换皮肤
		new SwitchSkin().setVisible(true);
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		//新建下载触发事件
		new NewDownload().setVisible(true);

	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//开始按钮触发事件
		int startNum = jTable1.getSelectedRow();
		if (startNum != -1) {
			if (modelNum == 0) {
				ModelUser.getRunn(startNum).restart();
				ModelUser.setValue("正在下载", startNum, 0);
				//同时刷新正在下载
				String src = ModelUser.getRowUrl(startNum);
				int index = ModelUser.getRowDL(src);
				ModelUser.setValueDLModel("正在下载", index, 0);
			} else if (modelNum == 1) {
				ModelUser.getRunnDL(startNum).restart();
				ModelUser.setValueDLModel("正在下载", startNum, 0);
				//同时刷新全部任务
				String src = ModelUser.getRowUrlDL(startNum);
				int index = ModelUser.getRow(src);
				ModelUser.setValue("正在下载", index, 0);
			}
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//正在下载触发事件
		jTable1.setModel(ModelUser.dateModelDownloading);
		modelNum = 1;
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//全部任务触发事件
		jTable1.setModel(ModelUser.dateModel);
		modelNum = 0;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

	public static void setSkin() {
		((JImagePane) jPanel1).setBackgroundImage(image);
	}

	private void setWindowIcon() {
		Image windowIcon = Toolkit.getDefaultToolkit().getImage(
				"img/icon.png");
		setIconImage(windowIcon);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JComboBox jComboBox1;
	public static  javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JToolBar jToolBar2;
	// End of variables declaration//GEN-END:variables

}